language: python
python: 3.7
sudo: false
env:
 - TOXENV=py37

install:
    - sudo apt-get install python-tk
    - sudo apt-get install pandoc
    - pip install -U tox twine wheel codecov flake8
    - pip install travis-sphinx
    - pip install -r requirements.txt
    - pip install -r docs/requirements.txt
    - python setup.py develop

before_script:
    - "export DISPLAY=:99"
    - sleep 3

services:
    - xvfb

script:
    - tox
    - travis-sphinx build -n

after_success:
    - codecov
    - flake8 cogitare/
    - travis-sphinx deploy

cache:
  directories:
    - $HOME/.cache/pip
